const config: SiteConfig = {
  name: "St. Mark's Hospital",

  slug: "smh",

  zones: {
    main: {
      slug: "main",
      name: "Main Rotation",
      type: "dual",
      superZone: "main",
      triggerSkip: false,
    },
    ft: {
      slug: "ft",
      name: "Orange - Fast Track",
      type: "simple",
      superZone: "main",
      triggerSkip: true,
    },
    off: {
      slug: "off",
      name: "Off Rotation",
      type: "list",
      triggerSkip: false,
    },
  },

  zoneOrder: ["main", "ft", "off"],

  schedule: [
    { name: "6 am - 3 pm", bonus: 2, joins: "main", reset: true },
    { name: "6 am - 3 pm APP", bonus: 1, joins: "main" },
    { name: "8 am - 5 pm", bonus: 2, joins: "main" },
    { name: "11 am - 8 pm", bonus: 2, joins: "main" },
    { name: "3 pm - 11 pm", bonus: 2, joins: "main" },
    { name: "3 pm - Midnight APP", bonus: 1, joins: "main" },
    { name: "7 pm - 3 am APP", bonus: 1, joins: "main" },
    { name: "5 pm - 1 am", bonus: 2, joins: "main" },
    { name: "11 pm - 6 am", bonus: 2, joins: "main" },
  ],

  providers: [
    { last: "Baretela", first: "Tracie", role: "app" },
    { last: "Blake", first: "Kelly", role: "physician" },
    { last: "Bown", first: "Deanna", role: "app" },
    { last: "Carmack", first: "Brian", role: "physician" },
    { last: "Cheever", first: "Shelley", role: "app" },
    { last: "Christensen", first: "Mark", role: "physician" },
    { last: "Conca", first: "Rocco", role: "app" },
    { last: "Cross", first: "Taylor", role: "app" },
    { last: "Dastrup", first: "Brigham", role: "physician" },
    { last: "DeWeerd", first: "Pete", role: "physician" },
    { last: "Denson", first: "Dave", role: "physician" },
    { last: "Erbach", first: "Craig", role: "physician" },
    { last: "Eller", first: "Dave", role: "physician" },
    { last: "Fox", first: "Julie", role: "physician" },
    { last: "Grahlfs", first: "Phil", role: "physician" },
    { last: "Hama", first: "Erinn", role: "physician" },
    { last: "Hardin", first: "Jeff", role: "physician" },
    { last: "Hart", first: "Mike", role: "physician" },
    { last: "Heinlein", first: "Danielle", role: "app" },
    { last: "Hollifield", first: "Matt", role: "physician" },
    { last: "Kamba", first: "Patrick", role: "physician" },
    { last: "Kasavana", first: "Brian", role: "physician" },
    { last: "Lawyer", first: "Thomas", role: "physician" },
    { last: "Lemon", first: "Anthon", role: "physician" },
    { last: "Lempit", first: "Hilary", role: "app" },
    { last: "Li", first: "Helen", role: "physician" },
    { last: "McNeill", first: "Josie", role: "app" },
    { last: "Merchant", first: "Azher", role: "physician" },
    { last: "Mooth", first: "Steve", role: "physician" },
    { last: "Mueller", first: "Trent", role: "physician" },
    { last: "Nicolai", first: "Rachelle", role: "physician" },
    { last: "Oleskey", first: "Zac", role: "physician" },
    { last: "Paradise", first: "Mark", role: "physician" },
    { last: "Park", first: "Tammy", role: "physician" },
    { last: "Porter", first: "Jacob", role: "physician" },
    { last: "Raborn", first: "Laurie", role: "physician" },
    { last: "Rodriguez", first: "Alec", role: "app" },
    { last: "Rogers", first: "Legrand", role: "physician" },
    { last: "Shaw", first: "Tyler", role: "app" },
    { last: "Shumway", first: "Jordan", role: "app" },
    { last: "Smith", first: "Maiya", role: "physician" },
    { last: "Stevens", first: "Mark", role: "physician" },
    { last: "Stiles", first: "Adam", role: "physician" },
    { last: "Voros", first: "Jeremy", role: "physician" },
    { last: "Wiesley", first: "Brett", role: "physician" },
    { last: "Wolfe", first: "Matt", role: "physician" },
    { last: "Yeates", first: "Todd", role: "physician" },
    { last: "Doc - Not Listed", first: "", role: "physician" },
    { last: "APP - Not Listed", first: "", role: "app" },
  ],

  rooms: [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "27",
    "28",
    "29",
    "30",
    "101",
    "102",
    "103",
    "104",
    "105",
    "106",
    "107",
    "108",
    "109",
    "110",
    "Hall A",
    "Hall B",
    "Hall C",
    "Hall D",
    "Hall E",
    "Hall F",
  ],
};

export default config;
